### ISSUE TITLE
Update from a version without device tracker

### ISSUE THREAD

**Issue by h4nc** [robmarkcole/Hue-sensors-HASS#104]
Hi,

I'd like to update to the newest version. I have 0.7 running. I do not have the device tracker component part in this version (don't know if it wasn't there or I did not install it).

Now I'd like to update. Do I need to copy and setup the device_tracker part too, or is it enough to copy the sensor file?
What is the device_tracker part for?

**Comment by yottatsa** [comment]
0.7 has no `device_tracker`. Instead it exports the Geofence data as a `sensor`.

`device_tracker` is exporting the same presence data using different entity:

<img width="357" alt="screenshot 2019-01-06 at 19 13 41" src="https://user-images.githubusercontent.com/68171/50740502-48529500-11e7-11e9-8c5e-15bdecb6fe82.png">

To start using it, simply copy the [file](https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_components/device_tracker/hue.py) to the `custom_components/device_tracker/hue.py`.

**Comment by h4nc** [comment]
Do to update the component it is enough to copy the sensor file.
I don‘t need the device tracking part. I use the app to revive commands from my hue remote (nothing else).

Just asking because I‘m not sure if the component only works when both parts are installed.

Side question:
I use an nmap sensor to track devices. Are there any advantages using this component to track.
This would use the hue app to track the devices?

**Comment by yottatsa** [comment]
It's enough to copy only one file.

Side question answer:
I'm still trying to figure out what is best, since I'm using `nmap`, `ios`, and `hue` to track and all of them are far from perfect. `nmap` is very bad at night and flapping all the time, `ios` sometimes stop updating the data until you re-open app's settings, and `hue` sometimes just stuck. :(

**Comment by h4nc** [comment]
Nmap doesn’t work that bad for me. But I have to say that I set it up to go to „away“ after the device is not seen for 10 minutes.

Going down to 5min does a lot of toggling. 
I‘m fine with 10min offset.

So the hue device tracker is another way to track the devices.
Do you know how it works?
What are the main differences between the services?

- nmap looks if a certain IP is logged in the network 
- iOS?
- hue?

**Comment by yottatsa** [comment]
Hue App uses Geofence to track when do you leave/come back home efficiently. It exports this data to the `sensors` API, so Hue could trigger the lights when you comes back. However, sometimes it misses the geofence event and stuck in the wrong state and you have no idea how to unstuck it.

`nmap` is good with this 10 min offset, but it still loses my phone at night (seems that iPhone loses Wi-FI in the Bedroom).

`ios` uses geofences and periodic updates, but sometimes loses authentication token.

**Comment by h4nc** [comment]
Why does life360 not drain the battery? As I saw this an app, so it will have gps tracking, right? Also every device hast have this app installed and (maybe) has to be relighted in after an app update.

**Comment by Mariusthvdb** [comment]
don't ask me why, but since people here were discussing the iOS tracker, I thought it useful to add this to the considered options.
In my setting, we had 4 iOS trackers depleting the battery more than twice a day, with settings fully enabled. This caused people to be unreachable.... and made them irritable and turn off the tracker...

Testing the life360 app, even with fully enabled notifications and tracking options don't seem to hair the battery at all. Not sure how it compares to a new and app-less phone, but compared to the iOS tracker its a no-brainer.

The CC adds some very nice details to this, and makes using it a snap.

But most importantly: no more continuous switching between home/not_home, which makes automations finally reliable.

**Comment by h4nc** [comment]
Thanks, it great know which options we do have.
