### ISSUE TITLE
The Great Migration

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#117]
As [per this announcement](https://developers.home-assistant.io/blog/) it is likely that the custom component will need to be refactored for HA 0.87. I actually think the effort would be better spent submitting an official component to HA.  I will leave this issue here as a notice that we are aware, so that its not necessary to have the same conversation a dozen times on the forum. Cheers

**Comment by glassbase** [comment]
I couldn't get mine to work as hue/sensor.py... I moved it to hue_custom/sensor.py and updated my sensors.yaml to `hue_custom:` and it worked. Whether that is the proper way - probably not - but hey it works.

**Comment by claytonjn** [comment]
`hue/sensor.py` and `hue/binary_sensor.py` is working fine for me.

**Comment by robmarkcole** [comment]
OK this appears to be a striaghtforward fix then

**Comment by Sanderhuisman** [comment]
I'm afraid it won't be an easy fix in the future anymore. Since pull request [#21070](https://github.com/home-assistant/home-assistant/pull/21070) HA will not allow partial overlay anymore. Therefore the hue sensors need to either override the complete hue platform or the custom platform needs to be renamed...

**Comment by Mariusthvdb** [comment]
check @glassbase  solution for that, should be an easy fix with that.

custom_components/hue_custom/binary_sensor
custom_components/hue_custom/sensor
custom_components/hue_custom/device_tracker

or, since there are no native Hue sensors this might even be more adequate?:

custom_components/hue_sensors/binary_sensor
custom_components/hue_sensors/sensor
custom_components/hue_sensors/device_tracker

**Comment by aptonline** [comment]
@mariusthvdb I’m assuming you mean:

```custom_components/hue_custom/binary_sensor.py
custom_components/hue_custom/sensor.py
custom_components/hue_custom/device_tracker.py```

Your post could be confusing in that ``hue.py`` should go into a sub folder and not renamed for example ``hue.py`` to ``sensor.py``.

**Comment by Mariusthvdb** [comment]
yes, I meant this:

`custom_components/hue_custom/binary_sensor.py`
`custom_components/hue_custom/sensor.py`
`custom_components/hue_custom/device_tracker.py`

sorry for that.

but the current 3 files hue.py should be renamed to sensor.py, device_tracker.py and binary_sensor.py...

**Comment by yottatsa** [comment]
Todo:
* rename custom component
* make a pull request with initial naive merge

**Comment by warcanoid** [comment]
Nobody has written that you have to also change configuration.yaml from hue to hue_custom:
device_tracker:
  - platform: hue_custom

sensor:
    - platform: hue_custom

binary_sensor:
  - platform: hue_custom

**Comment by aptonline** [comment]
@warcanoid I think @glassbase made reference to it but thanks for structuring it :)

**Comment by warcanoid** [comment]
How to fix custom_updater to show hue? Must place custom_updater.json where?

**Comment by h4nc** [comment]
@warcanoid see https://github.com/robmarkcole/Hue-sensors-HASS/issues/118

Doesn’t look that good

**Comment by warcanoid** [comment]
@h4nc so must wait for update?

**Comment by h4nc** [comment]
Probably yes, but I don’t know.
