### ISSUE TITLE
Drop support for custome_updater

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#149]
Now that we have HACS, people should use this. Address this in a month

**Comment by Mariusthvdb** [comment]
HI,

Would you please consider keeping the version number in the file? Not because of custom_updater, but some of us don't use HACS, and wait for an official way of handling versioning. Updating is done manually in that case, and it is a great help if the version is in the file

Right now, checking the file without makes it rather difficult to see, other than checking the file date.

HACS has a lot of system implications and I for one would like to wait and see for a bit.

So, please consider commenting version: 1.6 in the files ?

thanks!

**Comment by robmarkcole** [comment]
How do you mean 'manually'? If you are watching the repo and get alerts when a new version is available, why would that info need to be in the file also? 

I'm happy to consider this if there is a good reason, but it is one more step which the dev has to remember to do (update the version numbers in the files) and sometimes they forget!

**Comment by Mariusthvdb** [comment]
sure, manually I mean checking the version info In the actual file, and dl ing the file from your repo. We have been forced to change files in the past , test stops now and again, and re-installing different versions, depending on the state of the files in development, and not forget HA version (great migration)
Having used th custom_updater before, with its frequent changing configuration demands, makes me a bit weary fully relying on yet another custom component (which HACS) is in it self of course.

Simply dl'ing a file with the correct version number and replacing the older file, is easiest, and hassle free, and doesn't need 3d party software (add-ons).

Hope this is a good enough reason to maintain what has been done before ;-)

**Comment by robmarkcole** [comment]
OK we can add back in the version on next release. If you think you are weary with this component imagine how I feel..! :-)
