### ISSUE TITLE
Integration completely broken in 2016.6.0

### ISSUE THREAD

**Issue by cairon-ha** [robmarkcole/Hue-sensors-HASS#253]
Hi there,

unfortunately is this integration completely broken in 2016.6.0

The biggest lost is that as of today no switch is working any longer because it is only supported by this integration here.

Although only this integration can handle groups.

As of now no light is working anymore here!

Greets
Cairon

**Comment by Tiippex** [comment]
Check the readme. I think no one is going to fix anything here. There are alternatives for this:

PLEASE BE ADVISED: you are strongly encouraged to use the official Hue sensor integration, and cease using this custom integration.

Longer explanation: sensor support in the official hue integration is more feature-complete than this custom integration, and if you're already using Hue-remotes-HASS, then the refresh rate for sensors in the official integration will be automatically the fastest possible. Since we want to migrate users to the official integration, please do not open feature request issues or create PR adding new functionality to this custom integration, as they will not be considered. This custom integration will remain available until the next breaking change with Home Assistant, at which point this repo will be archived.

**Comment by CanD42** [comment]
I'd like to use the default motion sensor implementation but I'm relying on other sensor attributes like temperature and light_level to trigger different scenes for instance. How can these additional attributes be added to the default sensors?

**Comment by Tiippex** [comment]
What's wrong with the normal temperature and light sensor from the hue motion sensor:
![image](https://user-images.githubusercontent.com/16509128/121431597-e67b5400-c979-11eb-85a7-1f6d893b97e5.png)

I'm not sure if it's possible to create your own sensor from sensor attributes.

**Comment by CanD42** [comment]
Ah nice one, I wasn't aware that the motion sensor is splitted up into 3 sensors. I have to restructure my appdaemon code now.
yes, you can define your own sensors base sensor attributes like this:

      kuche_threshold:
        friendly_name: 'Küche Threshold'
        value_template: '{{states.sensor.kuche_sensor_light_level.attributes.threshold_dark}}'

**Comment by robmarkcole** [comment]
Can I close this?
