### ISSUE TITLE
Potential configuration change in 0.62

### ISSUE THREAD

**Issue by mf-social** [robmarkcole/Hue-sensors-HASS#37]
Hey,

So, I copied everything over before upgrading to 0.62 and when I upgraded and restarted I lost all my groups (display was just default_view).  I use custom_ui so initially I thought it was that, but after all sorts of digging I couldn't find anything.  Whilst doing this digging I found an entry in the log saying something like "could not set up sensor.hue" (wish I'd jotted the error down, but I still didn't think it was anything to do with this).  So I quickly commented out the lines:

```
sensor:
  - platform: hue
```

...just so that I could grep for errors on the next restart.

Anyway, next restart all my groups came back.  Thinking I'd fixed the problem elsewhere I re-enabled  the sensor, and promptly lost all my groups again.  I've now commented that out, and I have my groups back, but the sensors are still working (even with it commented out).

I also cannot recreate the error message when I re-include  the sensor line, but basically I don't seem to need the sensor in my config for the sensors to appear and work, and actually including the lines has the bizarre side effect of preventing all my groups from loading (with no obvious errors that I can find).

Any thoughts?

**Comment by mf-social** [comment]
My config is all on my github if you want to see - but to confirm I have no 
```
sensor:
  - platform: hue
```

anywhere in my config, and the sensors are working perfectly.

I do have both parts of the custom_component in my custom_components directory (although I am wondering if I can remove the sensor folder).

If I add the above ines back in all my groups fail to load with no error messages pertinent to anything to do with groups or the sensor.

**Comment by robmarkcole** [comment]
Sounds like you could have it configured twice? I’ve not tried 0.62 myself yet.

**Comment by mf-social** [comment]
Nope, definitely not configured anywhere else.

It's like the sensor is hardcoded in the python somewhere?

**Comment by robmarkcole** [comment]
You could delete the database, restart, see if there are errors. Unfortunately without error messages I've no way to debug.

**Comment by robmarkcole** [comment]
_the sensor not showing up is named hobbyrummet sensor_

Checking the device id, this is `SML_2e-02` and there appears to be 2 SML sensors which will be assigned this id; one named `hobbyrummet sensor` and another named `bathroom downstairs sensor`.  This probably occurred by chance and is seen here because the user has so many sensors.

Solution: need to come up with a true unique id.

**Comment by robmarkcole** [comment]
I am afraid this can only be fixed with a change to the code.

**Comment by robmarkcole** [comment]
From @mf-social 

Robin,

STOP!

(pauses for effect - love a bit of drama 😉  )

In the other issue I said I think the sensor is somehow now hardcoded in the python.  **It is** (even if you don't know it, or it shouldn't be) but **the important thing is it's not a problem**.

Here's what I have done to check everything out, but if you need any more info then let me know....

I have grep'd my entire install to ensure that there are no erroneous references to sensor platform hue.

I completely removed both hue.py and sensor/hue.py from my system, I deleted the database and rebooted the pi.

No sensors as expected and, crucially, no errors complaining that it cannot set up the sensor hue platform, so there are definitely no references to it in my system

Re-add only the hue.py, restart homeassistant, **persistent notification complains that it cannot find sensor.hue**.  I have **not** re-included that platform, so it MUST be hard-coded in to your hue.py somewhere.

Reintroduce sensor/hue.py and all errors disappear, and the hue sensors return.

The only ting you need to do to fix this issue is **remove** the instruction to include

```
sensor:
  - platform: hue
```

As that is what is causing the problem (maybe an endless loop or something)

Hope this helps.

**Comment by robmarkcole** [comment]
Yes the modified hue hub component references the sensors platform, so throws an error if not present. See [here](https://github.com/robmarkcole/Hue-sensors-HASS/blob/cd5100203b3b90a1e567e8c24efd49aced5748c5/custom_components/hue.py#L32). 

Therefore, if you remove the hue sensors you also need to remove the modified hue hub.

**Comment by mf-social** [comment]
Yeah, you're missing the point.

If you include the lines 

```
sensor:
  - platform: hue 
```

It breaks the configuration. When you remove these lines it's far and the sensors still work.

**Comment by robmarkcole** [comment]
This may be a new issue in 0.62. Will reopen but see if others report the same behaviour before updating docs. I've yet to test 0.62.

**Comment by robmarkcole** [comment]
OK I updated to 0.62 an did not experience the issue you report. Will keep this open for time-being to see if anyone else has problems.

**Comment by mf-social** [comment]
Can you check if you still get the sensors working if you remove the sensor lines from your configuration?

Seems weird that I don't need them and will require further investigation at my end if it doesn't work elsewhere. 

Groups issue could be manifesting because all my config is in packages, but it only manifests when I reinclude the sensor lines.

**Comment by mf-social** [comment]
Just a quick update for you - I've had to rebuild my system thanks to SD card corruption, and in doing so I've obviously copied over configuration files, but not any of the databases or background stuff.

I stlll do not require the entry

```
sensor:
  - platform: hue
```

and my sensors are still working fine.

I have not tried reintroducing the lines to see if I lose my groups again, but I might when I get a bit more keyboard time at some point.

FYI.

**Comment by robmarkcole** [comment]
Hi Mark
I've updated the main README to mention that configuring the sensors is optional, due to discovery.
I'm leaving it there as an option as some people turn off discovery.
Cheers

**Comment by mf-social** [comment]
I don't use discovery - so it's not that.

Not to worry, my config is working. 👍
