### ISSUE TITLE
Device ID are not necessarily unique

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/Hue-sensors-HASS#40]
As identified by [this issue](https://github.com/robmarkcole/Hue-sensors-HASS/issues/37), device ID (`_key` in the code) of the form `SML_2e-02` are not necessarily unique, and the chance that 2 sensors will have the same device ID goes up with the number of sensors a user owns. 

Solution: come up with a true [unique device ID](https://github.com/robmarkcole/Hue-sensors-HASS/blob/cd5100203b3b90a1e567e8c24efd49aced5748c5/custom_components/sensor/hue.py#L30)

Currently:
```
_key = modelid + '_' + sensor['uniqueid'].split(':')[-1][0:5]
```

**Comment by sevenofnine-jni** [comment]
I see that you have found the problem. Is there anything I can do to help?

**Comment by robmarkcole** [comment]
Yes you can help, as we need to identify a unique device ID that can be used. You will see that Hue represents a single motion sensor (henceforth referred to as the parent sensor) as a group of three child sensors (motion, light level, temperature) each of which has as `uniqueid`.  I had observed that characters 0-5 in the final set separated by : appeared to link the three child sensors, so use those characters as the key to group them to the parent sensor. Clearly those 5 characters are not unique to a single parent sensor, so we need to identify the correct way of generating a key to associated child to parent sensors. 

The alternative is just to treat each child sensor as a unique sensor, and leave it to the user to group them in HA.

**Comment by sevenofnine-jni** [comment]
If you use this part of the id 00:17:88:01:02:13:db:2e it seems to be unique?

**Comment by sevenofnine-jni** [comment]
I broke out all sensors from my api responce and formated the text to easily see the id's and as far as I can see it is possible to use the part of the id I stated above. See this pastebin. https://pastebin.com/BvR4Ua6j

**Comment by mf-social** [comment]
Robin,

STOP!

(pauses for effect - love a bit of drama 😉  )

In the other issue I said I think the sensor is somehow now hardcoded in the python.  It is (even if you don't know it) but **the important thing is it's not a problem**.

Here's what I have done to check everything out, but if you need any more info then let me know....

I have grp'd my entire install to ensure that there are no erroneous referencess ot sensor platform hue.

I completely removed both hue.py and sensor/hue.py from my system, I deleted the database and rebooted the pi.

No sensors as expected and, crucially, no errors complaining that it cannot set up the sensor hue platform, so there are definitely no references to it in my system

Re-add only the hue.py, restart homeassistant, spersistent notification complains that it cannot find sensor.hue.  I have not reincluded that platform, so it MUST be hardcoded in to your hue.py.

Reintroduce sensor/hue.py and all errors disappear, and the hue sensors return.

The only ting you need to do to fix this issue is **remove** the instruction to include

```
sensor:
  - platform: hue
```

As that is what is causing the problem (maybe an endless loop or something)

Hope this helps.

**Comment by sevenofnine-jni** [comment]
Or why not use the complete unique id? All three child sensors share the same uniqueid except for the very last 4 digits that is stating what kind of sensor it is. 0400 = light, 0402 = temp and 0406 is motion.

**Comment by robmarkcole** [comment]
OK fixed in https://github.com/robmarkcole/Hue-sensors-HASS/commit/9b388ded4fa75b9834d3768423df5d04bea57217 and release v0.4, thanks!

**Comment by sevenofnine-jni** [comment]
Works great now. Thanks for the fix.
